# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8203179b669e6c040e2c88eed041bc204e3340f07cdb8c1c110bcdac6b5bb992e900bfdfc9666fe3f0056b2cd1275222f1e4ccbb613e982a3113247befb67e04

test:
  secret_key_base: 2a80056020fc4463acd006bbf8c74c4a52d6179167842407c1ad37dd04a03a6fb4910b8ad39ae164f4360f645ddaf9ebb0fc5cf93a14c596df406f39e303fe8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
